import { CustomTitle } from "@/utils/CustomTitle";
import Image from "next/image";

const PrivacyPolicyPage = () => {
    return (
        <>
            <div
                className="relative bg-cover bg-center  flex itemsp-center justify-center py-16 md:py-36"
                style={{
                    backgroundImage: `url('/images/corporate-services-geiss-property-scaled.jpg')`,
                }}
            >
                <div className="absolute inset-0 bg-gradient-to-t from-black via-transparent opacity-60"></div>
                <div className="relative z-10 text-center text-white">
                    <h1 className="text-4xl md:text-6xl lg:text-7xl mb-4 font-primary">Datenschutzerklärung</h1>
                </div>
            </div>
            {/* point 1 */}
            <div className="container-x pt-8">
                <Image width={140} height={100} src="/images/siegel-impressum-blau.png" alt="Divider Logo" className="pb-4" />
                <div className="pt-4">
                    <CustomTitle>1. Überblick über den Datenschutz</CustomTitle>
                    <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Allgemeine Informationen</h1>
                    <p className="font-secondary text-description pt-2">{`Die folgenden Informationen geben Ihnen einen einfachen Überblick darüber, was mit Ihren personenbezogenen Daten passiert, wenn Sie diese Website besuchen. Der Begriff "personenbezogene Daten" umfasst alle Daten, mit denen Sie persönlich identifiziert werden können. Für detaillierte Informationen zum Thema Datenschutz lesen Sie bitte unsere Datenschutzerklärung, die wir unter diesem Text eingefügt haben.`}</p>
                </div>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Datenerfassung auf dieser Website</h1>
                <h1 className="text-[#D3D3D3] text-xl font-semibold font-secondary">{`Wer ist für die Datenerfassung auf dieser Website verantwortlich (d. h. der "Verantwortliche")?`}</h1>
                <div className="text-left">
                    <p className="font-secondary text-description pt-2">{`Die Daten auf dieser Website werden vom Betreiber der Website verarbeitet, dessen Kontaktdaten Sie unter dem Abschnitt "Angaben zum Verantwortlichen (im Sinne der DSGVO)" in dieser Datenschutzerklärung finden.`}</p>
                </div>

                <h1 className="text-[#D3D3D3] text-xl font-semibold font-secondary py-2">Wie erfassen wir Ihre Daten?</h1>
                <p className="font-secondary text-description ">{`Wir erfassen Ihre Daten, wenn Sie sie uns mitteilen. Dies kann z.B. durch das Ausfüllen unseres Kontaktformulars geschehen.

                    Andere Daten werden automatisch oder nach Ihrer Einwilligung beim Besuch der Website durch unsere IT-Systeme erfasst. Diese Daten umfassen in erster Linie technische Informationen (z.B. Webbrowser, Betriebssystem oder Zeitpunkt des Seitenaufrufs). Diese Informationen werden automatisch erfasst, wenn Sie diese Website besuchen.`}</p>
                <h1 className="text-[#D3D3D3] text-xl font-semibold font-secondary py-2">Zu welchen Zwecken nutzen wir Ihre Daten?</h1>
                <p className="font-secondary text-description ">{`Ein Teil der Informationen dient dazu, eine fehlerfreie Bereitstellung der Website zu gewährleisten. Andere Daten können verwendet werden, um Ihr Nutzerverhalten zu analysieren.`}</p>
                <h1 className="text-[#D3D3D3] text-xl font-semibold font-secondary py-2">Welche Rechte haben Sie bezüglich Ihrer Daten?</h1>
                <p className="font-secondary text-description ">{`Sie haben jederzeit das Recht, Auskunft über die Herkunft, die Empfänger und den Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten, ohne dafür eine Gebühr zu zahlen. Sie haben auch das Recht, die Berichtigung oder Löschung Ihrer Daten zu verlangen. Wenn Sie in die Datenverarbeitung eingewilligt haben, haben Sie das Recht, diese Einwilligung jederzeit zu widerrufen, was die zukünftige Datenverarbeitung betrifft. Außerdem haben Sie das Recht, unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer Daten zu verlangen. Darüber hinaus haben Sie das Recht, eine Beschwerde bei der zuständigen Aufsichtsbehörde einzureichen.`}</p>

                <p className="font-secondary text-description ">Zögern Sie bitte nicht, uns jederzeit zu kontaktieren, wenn Sie Fragen zu diesem oder anderen datenschutzbezogenen Themen haben.</p>
            </div>

            {/* point 2 */}
            <div className="container-x pt-4">
                <CustomTitle>2. Hosting</CustomTitle>
                <p className="font-secondary text-description">Wir hosten den Inhalt unserer Website bei folgendem Anbieter:</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Externes Hosting</h1>
                <p className="font-secondary text-description pt-2">{`Diese Website wird extern gehostet. Die auf dieser Website erhobenen personenbezogenen Daten werden auf den Servern des Hosts gespeichert. Dazu können unter anderem IP-Adressen, Kontaktanfragen, Metadaten und Kommunikationen, Vertragsinformationen, Kontaktdaten, Namen, Webseitenzugriffe und andere durch eine Webseite generierte Daten gehören.`}</p>
                <p className="font-secondary text-description pt-2">{`Das externe Hosting dient der Erfüllung des Vertrags mit unseren potenziellen und bestehenden Kunden (Art. 6 Abs. 1 lit. b DSGVO) und im Interesse einer sicheren, schnellen und effizienten Bereitstellung unserer Online-Dienste durch einen professionellen Anbieter (Art. 6 Abs. 1 lit. f DSGVO). Sofern eine entsprechende Einwilligung eingeholt wurde, erfolgt die Verarbeitung ausschließlich auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TTDSG, soweit die Einwilligung das Speichern von Cookies oder den Zugriff auf Informationen im Endgerät des Nutzers (z. B. Geräte-Fingerprinting) im Sinne des TTDSG umfasst. Diese Einwilligung kann jederzeit widerrufen werden.`}</p>
                <p className="font-secondary text-description pt-2">{`Folgende Serviceproider verarbeitet/verarbeiten Ihre Daten.`}</p>

                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Datenerfassung auf dieser Website</h1>

                <h1 className="text-[#D3D3D3] text-xl font-semibold font-secondary py-2">{`Wer ist für die Datenerfassung auf dieser Website verantwortlich (d. h. der "Verantwortliche")?`}</h1>
                <p className="font-secondary text-description pt-2">{`Die Daten auf dieser Website werden vom Betreiber der Website verarbeitet, dessen Kontaktdaten Sie unter dem Abschnitt "Angaben zum Verantwortlichen (im Sinne der DSGVO)" in dieser Datenschutzerklärung finden.`}</p>

                <h1 className="text-[#D3D3D3] text-xl font-semibold font-secondary py-2">{`Wie erfassen wir Ihre Daten?`}</h1>
                <p className="font-secondary text-description pt-2">{`Wir erfassen Ihre Daten, wenn Sie sie uns mitteilen. Dies kann z.B. durch das Ausfüllen unseres Kontaktformulars geschehen. Andere Daten werden automatisch oder nach Ihrer Einwilligung beim Besuch der Website durch unsere IT-Systeme erfasst. Diese Daten umfassen in erster Linie technische Informationen (z.B. Webbrowser, Betriebssystem oder Zeitpunkt des Seitenaufrufs). Diese Informationen werden automatisch erfasst, wenn Sie diese Website besuchen.`}</p>

                <h1 className="text-[#D3D3D3] text-xl font-semibold font-secondary py-2">{`Datenverarbeitung`}</h1>

                <p className="font-secondary text-description pt-2">{`Wir haben eine Vereinbarung über die Auftragsdatenverarbeitung (ADV) für die Nutzung des oben genannten Dienstes abgeschlossen. Dies ist ein durch Datenschutzgesetze vorgeschriebener Vertrag, der garantiert, dass personenbezogene Daten unserer Websitebesucher nur nach unseren Anweisungen und in Übereinstimmung mit der DSGVO verarbeitet werden.`}</p>

                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Datenerfassung auf dieser Website</h1>
                <h1 className="text-[#D3D3D3] text-xl font-semibold font-secondary">{`Wer ist für die Datenerfassung auf dieser Website verantwortlich (d. h. der "Verantwortliche")?`}</h1>
                <div className="text-left">
                    <p className="font-secondary text-description pt-2">{`Die Daten auf dieser Website werden vom Betreiber der Website verarbeitet, dessen Kontaktdaten Sie unter dem Abschnitt "Angaben zum Verantwortlichen (im Sinne der DSGVO)" in dieser Datenschutzerklärung finden.`}</p>
                </div>

                <h1 className="text-[#D3D3D3] text-xl font-semibold font-secondary py-2">Wie erfassen wir Ihre Daten?</h1>
                <p className="font-secondary text-description ">{`Wir erfassen Ihre Daten, wenn Sie sie uns mitteilen. Dies kann z.B. durch das Ausfüllen unseres Kontaktformulars geschehen.

                    Andere Daten werden automatisch oder nach Ihrer Einwilligung beim Besuch der Website durch unsere IT-Systeme erfasst. Diese Daten umfassen in erster Linie technische Informationen (z.B. Webbrowser, Betriebssystem oder Zeitpunkt des Seitenaufrufs). Diese Informationen werden automatisch erfasst, wenn Sie diese Website besuchen.`}</p>
                <h1 className="text-[#D3D3D3] text-xl font-semibold font-secondary py-2">Zu welchen Zwecken nutzen wir Ihre Daten?</h1>
                <p className="font-secondary text-description ">{`Ein Teil der Informationen dient dazu, eine fehlerfreie Bereitstellung der Website zu gewährleisten. Andere Daten können verwendet werden, um Ihr Nutzerverhalten zu analysieren.`}</p>
                <h1 className="text-[#D3D3D3] text-xl font-semibold font-secondary py-2">Welche Rechte haben Sie bezüglich Ihrer Daten?</h1>
                <p className="font-secondary text-description ">{`Sie haben jederzeit das Recht, Auskunft über die Herkunft, die Empfänger und den Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten, ohne dafür eine Gebühr zu zahlen. Sie haben auch das Recht, die Berichtigung oder Löschung Ihrer Daten zu verlangen. Wenn Sie in die Datenverarbeitung eingewilligt haben, haben Sie das Recht, diese Einwilligung jederzeit zu widerrufen, was die zukünftige Datenverarbeitung betrifft. Außerdem haben Sie das Recht, unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer Daten zu verlangen. Darüber hinaus haben Sie das Recht, eine Beschwerde bei der zuständigen Aufsichtsbehörde einzureichen.`}</p>

                <p className="font-secondary text-description ">Zögern Sie bitte nicht, uns jederzeit zu kontaktieren, wenn Sie Fragen zu diesem oder anderen datenschutzbezogenen Themen haben.</p>
            </div>

            {/* point 3 */}
            <div className="container-x pt-4">
                <CustomTitle>3. Allgemeine Informationen und Pflichtinformationen</CustomTitle>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Datenschutz</h1>
                <p className="font-secondary text-description pt-2">{`Die Betreiber dieser Webseite und ihrer Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Daher behandeln wir Ihre personenbezogenen Daten vertraulich und im Einklang mit den gesetzlichen Datenschutzvorschriften und dieser Datenschutzerklärung.`}</p>
                <p className="font-secondary text-description pt-2">{`Wenn Sie diese Website nutzen, werden verschiedene personenbezogene Daten gesammelt. Personenbezogene Daten sind Daten, mit denen Sie persönlich identifiziert werden können. In dieser Datenschutzerklärung wird erläutert, welche Daten wir sammeln sowie die Zwecke, für die wir diese Daten verwenden. Es wird auch erläutert, wie und zu welchem Zweck die Informationen gesammelt werden.`}</p>
                <p className="font-secondary text-description pt-2">{`Wir weisen hiermit darauf hin, dass die Übertragung von Daten über das Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein vollständiger Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Speicherdauer</h1>
                <p className="font-secondary text-description pt-2">{`Sofern keine spezifischere Speicherdauer in dieser Datenschutzerklärung festgelegt wurde, bleiben Ihre personenbezogenen Daten bei uns, bis der Zweck für ihre Erhebung nicht mehr besteht. Wenn Sie einen begründeten Löschungsantrag stellen oder Ihre Einwilligung zur Datenverarbeitung widerrufen, werden Ihre Daten gelöscht, es sei denn, es gibt andere rechtlich zulässige Gründe für die Speicherung Ihrer personenbezogenen Daten (z.B. steuer- oder handelsrechtliche Aufbewahrungsfristen); in diesem Fall erfolgt die Löschung, nachdem diese Gründe nicht mehr zutreffen.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Allgemeine Informationen zur Rechtsgrundlage der Datenverarbeitung auf dieser Webseite</h1>
                <p className="font-secondary text-description pt-2">{`Wenn Sie in die Datenverarbeitung eingewilligt haben, verarbeiten wir Ihre personenbezogenen Daten auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO oder Art. 9 Abs. 2 lit. a DSGVO, falls besondere Kategorien von Daten gemäß Art. 9 Abs. 1 DSGVO verarbeitet werden. Im Falle einer ausdrücklichen Einwilligung in die Übermittlung personenbezogener Daten an Drittländer basiert die Datenverarbeitung ebenfalls auf Art. 49 Abs. 1 lit. a DSGVO. Wenn Sie in die Speicherung von Cookies oder den Zugriff auf Informationen in Ihrem Endgerät (z.B. durch Geräte-Fingerprinting) eingewilligt haben, basiert die Datenverarbeitung zusätzlich auf § 25 Abs. 1 TTDSG. Die Einwilligung kann jederzeit widerrufen werden. Wenn Ihre Daten zur Erfüllung eines Vertrages oder zur Durchführung vorvertraglicher Maßnahmen benötigt werden, verarbeiten wir Ihre Daten auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO. Des Weiteren, wenn Ihre Daten zur Erfüllung einer rechtlichen Verpflichtung benötigt werden, verarbeiten wir sie auf Grundlage von Art. 6 Abs. 1 lit. c DSGVO. Darüber hinaus kann die Datenverarbeitung auf Grundlage unseres berechtigten Interesses nach Art. 6 Abs. 1 lit. f DSGVO erfolgen. Informationen zur jeweiligen Rechtsgrundlage in jedem Einzelfall finden Sie in den folgenden Absätzen dieser Datenschutzerklärung.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Informationen zur Datenübertragung in Drittländer, die datenschutzrechtlich nicht sicher sind, und zur Übertragung an US-Unternehmen, die nicht unter dem DPF zertifiziert sind</h1>
                <p className="font-secondary text-description pt-2">{`Wir verwenden unter anderem Technologien von Unternehmen, die sich in Drittländern befinden, die datenschutzrechtlich nicht sicher sind, sowie von US-Unternehmen, deren Anbieter nicht unter dem EU-US Datenschutzrahmen (DPF) zertifiziert sind. Wenn diese Tools aktiviert sind, können Ihre personenbezogenen Daten in diese Länder übertragen und dort verarbeitet werden. Wir möchten Sie darauf hinweisen, dass in diesen Drittländern kein Datenschutzniveau gewährleistet werden kann, das mit dem in der EU vergleichbar ist.`}</p>
                <p className="font-secondary text-description pt-2">{`Wir möchten darauf hinweisen, dass die USA als sicheres Drittland im Allgemeinen ein Datenschutzniveau bieten, das dem der EU vergleichbar ist. Datenübertragungen in die USA sind daher erlaubt, wenn der Empfänger unter dem „EU-US Datenschutzrahmen“ (DPF) zertifiziert ist oder angemessene zusätzliche Zusicherungen vorliegen. Informationen zu Übertragungen in Drittländer, einschließlich der Datenempfänger, finden Sie in dieser Datenschutzrichtlinie.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Empfänger personenbezogener Daten</h1>
                <p className="font-secondary text-description pt-2">{`Im Rahmen unserer Geschäftstätigkeit arbeiten wir mit verschiedenen externen Parteien zusammen. In einigen Fällen erfordert dies auch die Übermittlung personenbezogener Daten an diese externen Parteien. Wir geben personenbezogene Daten an externe Parteien nur weiter, wenn dies zur Erfüllung eines Vertrages erforderlich ist, wenn wir rechtlich dazu verpflichtet sind (z.B. Offenlegung von Daten an Steuerbehörden), wenn wir ein berechtigtes Interesse an der Offenlegung gemäß Art. 6 Abs. 1 lit. f DSGVO haben oder wenn eine andere Rechtsgrundlage die Offenlegung dieser Daten erlaubt. Bei der Nutzung von Verarbeitern geben wir personenbezogene Daten unserer Kunden nur auf der Grundlage eines gültigen Vertrags zur Auftragsdatenverarbeitung weiter. Im Falle einer gemeinsamen Verarbeitung wird eine Vereinbarung zur gemeinsamen Verarbeitung abgeschlossen.`}</p>
                <h1 className="text-[#D3D3D3] text-xl font-semibold font-secondary py-2">{`Widerruf Ihrer Einwilligung zur Datenverarbeitung`}</h1>
                <p className="font-secondary text-description pt-2">{`Viele Datenverarbeitungsvorgänge sind nur mit Ihrer ausdrücklichen Einwilligung möglich. Sie können eine bereits erteilte Einwilligung jederzeit widerrufen. Dies berührt die Rechtmäßigkeit der bis zum Widerruf erfolgten Datenerhebung nicht.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Widerspruchsrecht gegen die Datenerhebung in besonderen Fällen sowie gegen Direktwerbung (Art. 21 DSGVO)</h1>
                <p className="font-secondary text-description pt-2">{`WENN DIE DATENVERARBEITUNG AUF GRUNDLAGE VON ART. 6 ABS. 1 LIT. E ODER F DSGVO ERFOLGT, HABEN SIE JEDERZEIT DAS RECHT, AUS GRÜNDEN, DIE SICH AUS IHRER BESONDEREN SITUATION ERGEBEN, GEGEN DIE VERARBEITUNG IHRER PERSONENBEZOGENEN DATEN WIDERSPRUCH EINZULEGEN; DIES GILT AUCH FÜR EIN AUF DIESE BESTIMMUNGEN GESTÜTZTES PROFILING. DIE RECHTSGRUNDLAGE, AUF DER EINE VERARBEITUNG BERUHT, ENTNEHMEN SIE BITTE DIESER DATENSCHUTZERKLÄRUNG. WENN SIE WIDERSPRUCH EINLEGEN, WERDEN WIR IHRE BETROFFENEN PERSONENBEZOGENEN DATEN NICHT MEHR VERARBEITEN, ES SEI DENN, WIR KÖNNEN ZWINGENDE SCHUTZWÜRDIGE GRÜNDE FÜR DIE VERARBEITUNG NACHWEISEN, DIE IHRE INTERESSEN, RECHTE UND FREIHEITEN ÜBERWIEGEN, ODER WENN DIE VERARBEITUNG DER GELTENDMACHUNG, AUSÜBUNG ODER VERTEIDIGUNG VON RECHTSANSPRÜCHEN DIENT (WIDERSPRUCH NACH ART. 21 ABS. 1 DSGVO).`}</p>
                <p className="font-secondary text-description pt-2">{`WENN IHRE PERSONENBEZOGENEN DATEN VERARBEITET WERDEN, UM DIREKTWERBUNG ZU BETREIBEN, HABEN SIE DAS RECHT, JEDERZEIT WIDERSPRUCH GEGEN DIE VERARBEITUNG SIE BETREFFENDER PERSONENBEZOGENER DATEN ZUM ZWECKE SOLCHER WERBUNG EINZULEGEN; DIES GILT AUCH FÜR DAS PROFILING, SOWEIT ES MIT SOLCHER DIREKTWERBUNG IN VERBINDUNG STEHT. WENN SIE WIDERSPRUCH EINLEGEN, WERDEN IHRE PERSONENBEZOGENEN DATEN ANSCHLIESSEND NICHT MEHR ZUM ZWECKE DER DIREKTWERBUNG VERWENDET (WIDERSPRUCH NACH ART. 21 ABS. 2 DSGVO).`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Recht zur Beschwerde bei der zuständigen Aufsichtsbehörde</h1>
                <p className="font-secondary text-description pt-2">{`Im Falle von Verstößen gegen die DSGVO steht den Betroffenen ein Beschwerderecht bei einer Aufsichtsbehörde zu, insbesondere in dem Mitgliedstaat ihres gewöhnlichen Aufenthalts, ihres Arbeitsplatzes oder des Ortes des mutmaßlichen Verstoßes. Das Recht zur Beschwerde besteht unabhängig von sonstigen verwaltungsrechtlichen oder gerichtlichen Rechtsbehelfen.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Recht auf Datenübertragbarkeit
                </h1>
                <p className="font-secondary text-description pt-2">{`Sie haben das Recht, Daten, die wir auf Grundlage Ihrer Einwilligung oder zur Erfüllung eines Vertrages automatisiert verarbeiten, in einem gängigen, maschinenlesbaren Format an sich oder an einen Dritten übergeben zu bekommen. Falls Sie die direkte Übertragung der Daten an einen anderen Verantwortlichen fordern, erfolgt dies nur, soweit es technisch machbar ist.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Auskunft, Berichtigung und Löschung von Daten</h1>
                <p className="font-secondary text-description pt-2">{`Im Rahmen der geltenden gesetzlichen Bestimmungen haben Sie jederzeit das Recht, Auskunft über Ihre gespeicherten personenbezogenen Daten, deren Herkunft und Empfänger sowie den Zweck der Datenverarbeitung zu erhalten und ggf. eine Berichtigung oder Löschung dieser Daten zu verlangen. Wenn Sie Fragen zu diesem Thema oder anderen Fragen zum Thema personenbezogene Daten haben, können Sie sich jederzeit an uns wenden.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Recht auf Einschränkung der Verarbeitung
                </h1>
                <p className="font-secondary text-description pt-2">{`Sie haben das Recht, eine Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Hierzu können Sie sich jederzeit an uns wenden. Das Recht auf Einschränkung der Verarbeitung besteht in folgenden Fällen:`}</p>
                <ol className="font-secondary text-description pt-2 list-disc space-y-4 ms-4">
                    <li>Wenn Sie die Richtigkeit Ihrer bei uns gespeicherten Daten bestreiten, benötigen wir in der Regel Zeit, um dies zu überprüfen. Während der Dauer der Prüfung haben Sie das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.</li>
                    <li>Wenn die Verarbeitung Ihrer personenbezogenen Daten unrechtmäßig geschah/geschieht, können Sie statt der Löschung die Einschränkung der Datenverarbeitung verlangen.</li>
                    <li>Wenn wir Ihre personenbezogenen Daten nicht mehr benötigen, Sie diese jedoch zur Ausübung, Verteidigung oder Geltendmachung von Rechtsansprüchen benötigen, haben Sie das Recht, statt der Löschung die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.</li>
                    <li>Wenn Sie Widerspruch nach Art. 21 Abs. 1 DSGVO eingelegt haben, müssen Ihre Rechte und unsere Rechte gegeneinander abgewogen werden. Solange noch nicht feststeht, wessen Interessen überwiegen, haben Sie das Recht, eine Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.</li>
                </ol>
                <p className="font-secondary text-description pt-2">{`Wenn Sie die Verarbeitung Ihrer personenbezogenen Daten eingeschränkt haben, dürfen diese Daten – abgesehen von ihrer Speicherung – nur mit Ihrer Einwilligung oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen oder zum Schutz der Rechte einer anderen natürlichen oder juristischen Person oder aus Gründen eines wichtigen öffentlichen Interesses der Europäischen Union oder eines Mitgliedstaats verarbeitet werden.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">SSL- und/oder TLS-Verschlüsselung</h1>
                <p className="font-secondary text-description pt-2">{`Aus Sicherheitsgründen und zum Schutz der Übertragung vertraulicher Inhalte, wie zum Beispiel Bestellungen oder Anfragen, die Sie an uns als Seitenbetreiber senden, nutzt diese Website entweder ein SSL- oder ein TLS-Verschlüsselungsprogramm. Sie können eine verschlüsselte Verbindung daran erkennen, dass die Adresszeile des Browsers von „http://“ auf „https://“ wechselt und an dem Schloss-Symbol in Ihrer Browserzeile.`}</p>

                <p className="font-secondary text-description pt-2">{`Wenn die SSL- oder TLS-Verschlüsselung aktiviert ist, können die Daten, die Sie an uns übermitteln, nicht von Dritten gelesen werden.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Ablehnung unerwünschter E-Mails</h1>

                <p className="font-secondary text-description pt-2">{`Hiermit widersprechen wir der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-E-Mails, vor.`}</p>
            </div>

            {/* point 4 */}
            <div className="container-x pt-4">
                <CustomTitle>4. Erfassung von Daten auf dieser Website
                    Cookies</CustomTitle>
                <p className="font-secondary text-description pt-2">{`Unsere Webseiten und Seiten verwenden sogenannte „Cookies“. Cookies sind kleine Datenpakete, die Ihr Gerät nicht beschädigen. Sie werden entweder temporär für die Dauer einer Sitzung (Session-Cookies) oder dauerhaft auf Ihrem Gerät gespeichert (permanente Cookies). Session-Cookies werden automatisch gelöscht, nachdem Sie Ihren Besuch beendet haben. Permanente Cookies bleiben auf Ihrem Gerät gespeichert, bis Sie diese aktiv löschen oder sie automatisch von Ihrem Webbrowser gelöscht werden.`}</p>
                <p className="font-secondary text-description pt-2">{`Cookies können von uns (First-Party-Cookies) oder von Drittanbietern (sogenannte Third-Party-Cookies) ausgegeben werden. Third-Party-Cookies ermöglichen die Integration bestimmter Dienste von Drittanbietern auf Webseiten (z.B. Cookies zur Abwicklung von Zahlungsdiensten).`}</p>
                <p className="font-secondary text-description pt-2">{`Cookies haben verschiedene Funktionen. Viele Cookies sind technisch notwendig, da gewisse Website-Funktionen ohne diese Cookies nicht funktionieren würden (z.B. die Warenkorbfunktion oder die Anzeige von Videos). Andere Cookies können zur Analyse des Nutzerverhaltens oder für Werbezwecke verwendet werden.`}</p>

                <p className="font-secondary text-description pt-2">{`Cookies, die für die Durchführung elektronischer Kommunikationsvorgänge, für die Bereitstellung bestimmter von Ihnen erwünschter Funktionen (z.B. für die Warenkorbfunktion) oder die notwendig sind zur Optimierung der Webseite (erforderliche Cookies), werden auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO gespeichert, sofern keine andere Rechtsgrundlage angegeben wird. Der Websitebetreiber hat ein berechtigtes Interesse an der Speicherung von Cookies zur technisch fehlerfreien und optimierten Bereitstellung seiner Dienste. Wenn eine Einwilligung zur Speicherung von Cookies und ähnlichen Erkennungstechnologien abgefragt wurde, erfolgt die Verarbeitung ausschließlich auf Grundlage dieser eingeholten Einwilligung (Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TTDSG); diese Einwilligung kann jederzeit widerrufen werden.`}</p>
                <p className="font-secondary text-description pt-2">{`Sie haben die Möglichkeit, Ihren Browser so einzustellen, dass Sie über das Setzen von Cookies informiert werden und Cookies nur in bestimmten Fällen akzeptieren. Sie können die Annahme von Cookies in bestimmten Fällen oder generell ausschließen sowie die Automatische Löschfunktion aktivieren, die Cookies beim Schließen des Browsers löscht. Wenn Cookies deaktiviert werden, können die Funktionen dieser Website eingeschränkt sein.`}</p>
                <p className="font-secondary text-description pt-2">{`Welche Cookies und Dienste auf dieser Webseite verwendet werden, finden Sie in dieser Datenschutzerklärung.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Consent with Borlabs Cookie</h1>
                <p className="font-secondary text-description pt-2">{`Our website uses the Borlabs consent technology to obtain your consent to the storage of certain cookies in your browser or for the use of certain technologies and for their data privacy protection compliant documentation. The provider of this technology is Borlabs GmbH, Rübenkamp 32, 22305 Hamburg, Germany (hereinafter referred to as Borlabs).`}</p>
                <p className="font-secondary text-description pt-2">{`Whenever you visit our website, a Borlabs cookie will be stored in your browser, which archives any declarations or revocations of consent you have entered. These data are not shared with the provider of the Borlabs technology.`}</p>
                <p className="font-secondary text-description pt-2">{`The recorded data shall remain archived until you ask us to eradicate them, delete the Borlabs cookie on your own or the purpose of storing the data no longer exists. This shall be without prejudice to any retention obligations mandated by law. To review the details of Borlabs’ data processing policies, please visit https://de.borlabs.io/kb/welche-daten-speichert-borlabs-cookie/`}</p>
                <p className="font-secondary text-description pt-2">{`We use the Borlabs cookie consent technology to obtain the declarations of consent mandated by law for the use of cookies. The legal basis for the use of such cookies is Art. 6(1)(c) GDPR`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Contact form</h1>
                <p className="font-secondary text-description pt-2">{`If you submit inquiries to us via our contact form, the information provided in the contact form as well as any contact information provided therein will be stored by us in order to handle your inquiry and in the event that we have further questions. We will not share this information without your consent.`}</p>
                <p className="font-secondary text-description pt-2">{`The processing of these data is based on Art. 6(1)(b) GDPR, if your request is related to the execution of a contract or if it is necessary to carry out pre-contractual measures. In all other cases the processing is based on our legitimate interest in the effective processing of the requests addressed to us (Art. 6(1)(f) GDPR) or on your agreement (Art. 6(1)(a) GDPR) if this has been requested; the consent can be revoked at any time.`}</p>
                <p className="font-secondary text-description pt-2">{`The information you have entered into the contact form shall remain with us until you ask us to eradicate the data, revoke your consent to the archiving of data or if the purpose for which the information is being archived no longer exists (e.g., after we have concluded our response to your inquiry). This shall be without prejudice to any mandatory legal provisions, in particular retention periods.`}</p>

                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Request by e-mail, telephone, or fax</h1>
                <p className="font-secondary text-description pt-2">{`If you contact us by e-mail, telephone or fax, your request, including all resulting personal data (name, request) will be stored and processed by us for the purpose of processing your request. We do not pass these data on without your consent.`}</p>
                <p className="font-secondary text-description pt-2">{`These data are processed on the basis of Art. 6(1)(b) GDPR if your inquiry is related to the fulfillment of a contract or is required for the performance of pre-contractual measures. In all other cases, the data are processed on the basis of our legitimate interest in the effective handling of inquiries submitted to us (Art. 6(1)(f) GDPR) or on the basis of your consent (Art. 6(1)(a) GDPR) if it has been obtained; the consent can be revoked at any time.`}</p>
                <p className="font-secondary text-description pt-2">{`The data sent by you to us via contact requests remain with us until you request us to delete, revoke your consent to the storage or the purpose for the data storage lapses (e.g. after completion of your request). Mandatory statutory provisions - in particular statutory retention periods - remain unaffected.`}</p>
            </div>

            {/* point 5 */}
            <div className="container-x pt-4">
                <CustomTitle>5. Social media</CustomTitle>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Facebook</h1>
                <p className="font-secondary text-description pt-2">{`We have integrated elements of the social network Facebook on this website. The provider of this service is Meta Platforms Ireland Limited, 4 Grand Canal Square, Dublin 2, Ireland. According to Facebook’s statement the collected data will be transferred to the USA and other third-party countries too.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`An overview of the Facebook social media elements is available under the following link: https://developers.facebook.com/docs/plugins/.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`If the social media element has been activated, a direct connection between your device and the Facebook server will be established. As a result, Facebook will receive information confirming your visit to this website with your IP address. If you click on the Facebook Like button while you are logged into your Facebook account, you can link content of this website to your Facebook profile. Consequently, Facebook will be able to allocate your visit to this website to your user account. We have to emphasize that we as the provider of the website do not receive any information on the content of the transferred data and its use by Facebook. For more information, please consult the Data Privacy Policy of Facebook at: https://de-de.facebook.com/privacy/explanation.`}</p>
                <p className="font-secondary text-description pt-2">{`If your approval (consent) has been obtained the use of the abovementioned service shall occur on the basis of Art. 6 Sect. 1 lit. a GDPR and § 25 TTDSG (German Telecommunications Act). Such consent may be revoked at any time. If your consent was not obtained, the use of the service will occur on the basis of our legitimate interest in making our information as comprehensively visible as possible on social media.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`Insofar as personal data is collected on our website with the help of the tool described here and forwarded to Facebook, we and Meta Platforms Ireland Limited, 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland are jointly responsible for this data processing (Art. 26 DSGVO). The joint responsibility is limited exclusively to the collection of the data and its forwarding to Facebook. The processing by Facebook that takes place after the onward transfer is not part of the joint responsibility. The obligations incumbent on us jointly have been set out in a joint processing agreement. The wording of the agreement can be found under: https://www.facebook.com/legal/controller_addendum. According to this agreement, we are responsible for providing the privacy information when using the Facebook tool and for the privacy-secure implementation of the tool on our website. Facebook is responsible for the data security of Facebook products. You can assert data subject rights (e.g., requests for information) regarding data processed by Facebook directly with Facebook. If you assert the data subject rights with us, we are obliged to forward them to Facebook.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">Data transmission to the US is based on the Standard Contractual Clauses (SCC) of the European Commission. Details can be found here: https://www.facebook.com/legal/EU_data_transfer_addendum, https://de-de.facebook.com/help/566994660333381 and https://www.facebook.com/policy.php.</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`The company is certified in accordance with the “EU-US Data Privacy Framework” (DPF). The DPF is an agreement between the European Union and the US, which is intended to ensure compliance with European data protection standards for data processing in the US. Every company certified under the DPF is obliged to comply with these data protection standards. For more information, please contact the provider under the following link: https://www.dataprivacyframework.gov/s/participant-search/participant-detail?contact=true&id=a2zt0000000GnywAAC&status=Active`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Instagram</h1>
                <p className="font-secondary text-description pt-2">{`We have integrated functions of the public media platform Instagram into this website. These functions are being offered by Meta Platforms Ireland Limited, 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland.`}</p>
                <p className="font-secondary text-description pt-2">{`If the social media element has been activated, a direct connection between your device and Instagram’s server will be established. As a result, Instagram will receive information on your visit to this website.`}</p>
                <p className="font-secondary text-description pt-2">{`If you are logged into your Instagram account, you may click the Instagram button to link contents from this website to your Instagram profile. This enables Instagram to allocate your visit to this website to your user account. We have to point out that we as the provider of the website and its pages do not have any knowledge of the content of the data transferred and its use by Instagram.`}</p>

                <p className="font-secondary text-description pt-2">{`If your approval (consent) has been obtained the use of the abovementioned service shall occur on the basis of Art. 6(1)(a) GDPR and § 25 TTDSG (German Telecommunications Act). Such consent may be revoked at any time. If your consent was not obtained, the use of the service will occur on the basis of our legitimate interest in making our information as comprehensively visible as possible on social media.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`Insofar as personal data is collected on our website with the help of the tool described here and forwarded to Facebook or Instagram, we and Meta Platforms Ireland Limited, 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland are jointly responsible for this data processing (Art. 26 DSGVO). The joint responsibility is limited exclusively to the collection of the data and its forwarding to Facebook or Instagram. The processing by Facebook or Instagram that takes place after the onward transfer is not part of the joint responsibility. The obligations incumbent on us jointly have been set out in a joint processing agreement. The wording of the agreement can be found under: https://www.facebook.com/legal/controller_addendum. According to this agreement, we are responsible for providing the privacy information when using the Facebook or Instagram tool and for the privacy-secure implementation of the tool on our website. Facebook is responsible for the data security of Facebook or Instagram products. You can assert data subject rights (e.g., requests for information) regarding data processed by Facebook or Instagram directly with Facebook. If you assert the data subject rights with us, we are obliged to forward them to Facebook.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`Data transmission to the US is based on the Standard Contractual Clauses (SCC) of the European Commission. Details can be found here: https://www.facebook.com/legal/EU_data_transfer_addendum, https://privacycenter.instagram.com/policy/ and https://de-de.facebook.com/help/566994660333381.`}</p>
                <p className="font-secondary text-description pt-2">{`For more information on this subject, please consult Instagram’s Data Privacy Declaration at: https://privacycenter.instagram.com/policy/.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`The company is certified in accordance with the “EU-US Data Privacy Framework” (DPF). The DPF is an agreement between the European Union and the US, which is intended to ensure compliance with European data protection standards for data processing in the US. Every company certified under the DPF is obliged to comply with these data protection standards. For more information, please contact the provider under the following link: https://www.dataprivacyframework.gov/s/participant-search/participant-detail?contact=true&id=a2zt0000000GnywAAC&status=Active`}</p>
            </div>

            {/* Point 6 */}
            <div className="container-x pt-4 pb-8">
                <CustomTitle>6. Plug-ins and Tools</CustomTitle>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">YouTube with expanded data protection integration</h1>
                <p className="font-secondary text-description pt-2">{`Our website embeds videos of the website YouTube. The website operator is Google Ireland Limited (“Google”), Gordon House, Barrow Street, Dublin 4, Ireland.`}</p>
                <p className="font-secondary text-description pt-2">{`We use YouTube in the expanded data protection mode. According to YouTube, this mode ensures that YouTube does not store any information about visitors to this website before they watch the video. Nevertheless, this does not necessarily mean that the sharing of data with YouTube partners can be ruled out as a result of the expanded data protection mode. For instance, regardless of whether you are watching a video, YouTube will always establish a connection with the Google Marketing Network.`}</p>
                <p className="font-secondary text-description pt-2">{`As soon as you start to play a YouTube video on this website, a connection to YouTube’s servers will be established. As a result, the YouTube server will be notified, which of our pages you have visited. If you are logged into your YouTube account while you visit our site, you enable YouTube to directly allocate your browsing patterns to your personal profile. You have the option to prevent this by logging out of your YouTube account.`}</p>
                <p className="font-secondary text-description pt-2">{`Furthermore, after you have started to play a video, YouTube will be able to place various cookies on your device or comparable technologies for recognition (e.g. device fingerprinting). In this way YouTube will be able to obtain information about this website’s visitors. Among other things, this information will be used to generate video statistics with the aim of improving the user friendliness of the site and to prevent attempts to commit fraud.`}</p>
                <p className="font-secondary text-description pt-2">{`Under certain circumstances, additional data processing transactions may be triggered after you have started to play a YouTube video, which are beyond our control.`}</p>
                <p className="font-secondary text-description pt-2">{`The use of YouTube is based on our interest in presenting our online content in an appealing manner. Pursuant to Art. 6(1)(f) GDPR, this is a legitimate interest. If appropriate consent has been obtained, the processing is carried out exclusively on the basis of Art. 6(1)(a) GDPR and § 25 (1) TTDSG, insofar the consent includes the storage of cookies or the access to information in the user’s end device (e.g., device fingerprinting) within the meaning of the TTDSG. This consent can be revoked at any time.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`For more information on how YouTube handles user data, please consult the YouTube Data Privacy Policy under: https://policies.google.com/privacy?hl=en.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`The company is certified in accordance with the “EU-US Data Privacy Framework” (DPF). The DPF is an agreement between the European Union and the US, which is intended to ensure compliance with European data protection standards for data processing in the US. Every company certified under the DPF is obliged to comply with these data protection standards. For more information, please contact the provider under the following link: https://www.dataprivacyframework.gov/s/participant-search/participant-detail?contact=true&id=a2zt000000001L5AAI&status=Active`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Google Fonts (local embedding)
                </h1>
                <p className="font-secondary text-description pt-2">{`This website uses so-called Google Fonts provided by Google to ensure the uniform use of fonts on this site. These Google fonts are locally installed so that a connection to Google’s servers will not be established in conjunction with this application.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`For more information on Google Fonts, please follow this link: https://developers.google.com/fonts/faq and consult Google’s Data Privacy Declaration under: https://policies.google.com/privacy?hl=en.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Font Awesome</h1>
                <p className="font-secondary text-description pt-2">{`This page uses Font Awesome for the uniform representation of fonts and symbols. Provider is Fonticons, Inc. 6 Porter Road Apartment 3R, Cambridge, Massachusetts, USA.`}</p>
                <p className="font-secondary text-description pt-2">{`When you call up a page, your browser loads the required fonts into its browser cache to display texts, fonts, and symbols correctly. For this purpose, the browser you use must connect to the servers of Font Awesome. This allows Font Awesome to know that your IP address has been used to access this website. The use of Font Awesome is based on Art. 6(1)(f) GDPR. We have a legitimate interest in the uniform presentation of the typeface on our website. If appropriate consent has been obtained, the processing is carried out exclusively on the basis of Art. 6(1)(a) GDPR and § 25 (1) TTDSG, insofar the consent includes the storage of cookies or the access to information in the user’s end device (e.g., device fingerprinting) within the meaning of the TTDSG. This consent can be revoked at any time.`}</p>
                <p className="font-secondary text-description pt-2">{`If your browser does not support Font Awesome, a standard font from your computer will be used.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`Further information about Font Awesome can be found in the Font Awesome privacy policy at: https://fontawesome.com/privacy.`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Google Maps</h1>
                <p className="font-secondary text-description pt-2">{`This website uses the mapping service Google Maps. The provider is Google Ireland Limited (“Google”), Gordon House, Barrow Street, Dublin 4, Ireland.`}</p>
                <p className="font-secondary text-description pt-2">{`To enable the use of the Google Maps features, your IP address must be stored. As a rule, this information is transferred to one of Google’s servers in the United States, where it is archived. The operator of this website has no control over the data transfer. In case Google Maps has been activated, Google has the option to use Google Fonts for the purpose of the uniform depiction of fonts. When you access Google Maps, your browser will load the required web fonts into your browser cache, to correctly display text and fonts.`}</p>
                <p className="font-secondary text-description pt-2">{`We use Google Maps to present our online content in an appealing manner and to make the locations disclosed on our website easy to find. This constitutes a legitimate interest as defined in Art. 6(1)(f) GDPR. If appropriate consent has been obtained, the processing is carried out exclusively on the basis of Art. 6(1)(a) GDPR and § 25 (1) TTDSG, insofar the consent includes the storage of cookies or the access to information in the user’s end device (e.g., device fingerprinting) within the meaning of the TTDSG. This consent can be revoked at any time.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`Data transmission to the US is based on the Standard Contractual Clauses (SCC) of the European Commission. Details can be found here: https://privacy.google.com/businesses/gdprcontrollerterms/ and https://privacy.google.com/businesses/gdprcontrollerterms/sccs/.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`For more information on the handling of user data, please review Google’s Data Privacy Declaration under: https://policies.google.com/privacy?hl=en.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`The company is certified in accordance with the “EU-US Data Privacy Framework” (DPF). The DPF is an agreement between the European Union and the US, which is intended to ensure compliance with European data protection standards for data processing in the US. Every company certified under the DPF is obliged to comply with these data protection standards. For more information, please contact the provider under the following link: https://www.dataprivacyframework.gov/s/participant-search/participant-detail?contact=true&id=a2zt000000001L5AAI&status=Active`}</p>
                <h1 className="text-white text-2xl md:text-3xl font-bold font-primary my-2">Google reCAPTCHA</h1>
                <p className="font-secondary text-description pt-2">{`We use “Google reCAPTCHA” (hereinafter referred to as “reCAPTCHA”) on this website. The provider is Google Ireland Limited (“Google”), Gordon House, Barrow Street, Dublin 4, Ireland.`}</p>

                <p className="font-secondary text-description pt-2">{`The purpose of reCAPTCHA is to determine whether data entered on this website (e.g., information entered into a contact form) is being provided by a human user or by an automated program. To determine this, reCAPTCHA analyzes the behavior of the website visitors based on a variety of parameters. This analysis is triggered automatically as soon as the website visitor enters the site. For this analysis, reCAPTCHA evaluates a variety of data (e.g., IP address, time the website visitor spent on the site or cursor movements initiated by the user). The data tracked during such analyses are forwarded to Google.`}</p>
                <p className="font-secondary text-description pt-2">{`reCAPTCHA analyses run entirely in the background. Website visitors are not alerted that an analysis is underway.`}</p>
                <p className="font-secondary text-description pt-2">{`Data are stored and analyzed on the basis of Art. 6(1)(f) GDPR. The website operator has a legitimate interest in the protection of the operator’s websites against abusive automated spying and against SPAM. If appropriate consent has been obtained, the processing is carried out exclusively on the basis of Art. 6(1)(a) GDPR and § 25 (1) TTDSG, insofar the consent includes the storage of cookies or the access to information in the user’s end device (e.g., device fingerprinting) within the meaning of the TTDSG. This consent can be revoked at any time.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`For more information about Google reCAPTCHA please refer to the Google Data Privacy Declaration and Terms Of Use under the following links: https://policies.google.com/privacy?hl=en and https://policies.google.com/terms?hl=en.`}</p>
                <p className="font-secondary text-description pt-2 overflow-x-auto">{`The company is certified in accordance with the “EU-US Data Privacy Framework” (DPF). The DPF is an agreement between the European Union and the US, which is intended to ensure compliance with European data protection standards for data processing in the US. Every company certified under the DPF is obliged to comply with these data protection standards. For more information, please contact the provider under the following link: https://www.dataprivacyframework.gov/s/participant-search/participant-detail?contact=true&id=a2zt000000001L5AAI&status=Active`}</p>
            </div>
        </>
    );
}

export default PrivacyPolicyPage; 